# Generated by Django 4.1.7 on 2023-02-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
